import type { LucideIcon } from "lucide-react";
import {
  Building2,
  Stethoscope,
  UtensilsCrossed,
  Truck,
  ShoppingBag,
  Factory,
  Home,
  Briefcase,
  Cpu,
  Globe,
  Hammer,
  HardHat,
  Wrench,
  Tractor,
  Leaf,
  Smile,
  HandCoins,
  Baby,
  Pizza,
  Hotel,
  Coffee,
  Car,
  Bus,
  Plane,
  Scissors,
  Dumbbell,
  Store,
  ShoppingCart,
  Package,
  Boxes,
  Cog,
  Building,
  Banknote,
  Scale,
  Calculator,
  Laptop,
  CreditCard,
  Receipt,
  TrendingUp,
  LineChart,
  Megaphone,
  Sparkles,
} from "lucide-react";

export type Service = {
  slug: string;
  title: string;
  icon: LucideIcon;
  tagline: string;
  description: string;
  bullets: string[];
  highlight: string;
};

export type Industry = {
  slug: string;
  label: string;
  icon: LucideIcon;
  hero: string;
  intro: string;
  services: Service[];
};

const make = (
  slug: string,
  title: string,
  icon: LucideIcon,
  tagline: string,
  description: string,
  bullets: string[],
  highlight: string,
): Service => ({ slug, title, icon, tagline, description, bullets, highlight });

export const INDUSTRIES: Industry[] = [
  {
    slug: "construction",
    label: "Construction",
    icon: Building2,
    hero: "Capital that breaks ground.",
    intro:
      "From Brickell mid-rise builds to Doral light-industrial expansion, we structure financing that keeps Miami crews moving and projects on schedule across South Florida's most active development pipeline.",
    services: [
      make(
        "commercial-construction-loan",
        "Commercial Construction Loan",
        Hammer,
        "Ground-up & renovation projects",
        "Multi-draw financing aligned to your Miami construction schedule with interest-only periods during the build phase.",
        ["Up to 80% LTC", "12-36 month terms", "Convertible to permanent financing"],
        "Funding $250K-$25M",
      ),
      make(
        "equipment-financing",
        "Construction Equipment Financing",
        HardHat,
        "Excavators, cranes, loaders",
        "Finance new or used heavy equipment with the equipment itself serving as collateral, preserving working capital for jobs.",
        ["100% financing available", "Section 179 eligible", "Approvals in 24-48 hours"],
        "Rates from 6.99%",
      ),
      make(
        "equipment-loans",
        "Equipment Loans",
        Wrench,
        "Own outright after the final payment",
        "Fixed-rate loans designed for contractors who want to build equity in their fleet without leasing handoffs.",
        ["Fixed monthly payments", "Terms 2-7 years", "Tax deduction advantages"],
        "$10K-$5M",
      ),
    ],
  },
  {
    slug: "healthcare",
    label: "Healthcare",
    icon: Stethoscope,
    hero: "Funding for those who care.",
    intro:
      "Specialized lending for Miami medical, dental, aesthetics and childcare practices: from buy-ins to build-outs and the latest imaging, laser and body-contouring equipment that South Florida is known for.",
    services: [
      make(
        "medical-practice-loans",
        "Medical Practice Loans",
        Stethoscope,
        "Clinics & physician groups",
        "Acquisition, partner buy-in, expansion and working capital tailored to the rhythms of insurance reimbursements and Miami's dense specialty-care market.",
        ["Up to 100% project financing", "Terms up to 10 years", "Deferred payment options"],
        "$50K-$7M",
      ),
      make(
        "dental-practice-loans",
        "Dental Practice Loans",
        Smile,
        "Equipment, expansion & acquisition",
        "Finance chairs, CBCT imaging, build-outs or a full practice purchase with structures designed for Brickell, Coral Gables and Aventura DSOs and solo practices.",
        ["Chairs, imaging & software", "Practice acquisition", "Refinance existing debt"],
        "Rates from 7.25%",
      ),
      make(
        "sba-loan-for-daycare",
        "SBA Loan for Daycare",
        Baby,
        "Childcare facility financing",
        "SBA 7(a) and 504 loans for licensed Miami-Dade childcare operators: real estate, renovation, equipment and working capital in one package.",
        ["10% down on real estate", "25-year amortization", "Low fixed rates"],
        "Up to $5M",
      ),
      make(
        "professional-services",
        "Allied Professional Loans",
        HandCoins,
        "Aesthetics, therapy, optometry",
        "Capital for the wider care economy: medical aesthetics, veterinary expansion, physical therapy clinics, behavioral health and Miami's growing wellness sector.",
        ["No collateral options", "Bridge & permanent financing", "Cash-out refinance"],
        "48-hour approvals",
      ),
    ],
  },
  {
    slug: "restaurants",
    label: "Restaurants & Hospitality",
    icon: UtensilsCrossed,
    hero: "Fuel the next service.",
    intro:
      "Working capital and equipment financing for Miami restaurants, food trucks, cafés and hospitality: from Calle Ocho cafeterías to South Beach hotels, sized to the realities of South Florida hospitality margins.",
    services: [
      make(
        "restaurant-loans",
        "Restaurant Loans",
        UtensilsCrossed,
        "Fit-out, expansion & equipment",
        "Open the second location, refresh the dining room or weather a slow season with capital structured for Miami hospitality cash flow.",
        ["Daily, weekly or monthly payments", "Same-day approvals", "No equity required"],
        "$25K-$2M",
      ),
      make(
        "hotel-loans",
        "Hotel Loans",
        Hotel,
        "Acquisition & PIP renovation",
        "Capital for flagged and independent properties across South Beach, Brickell and the Keys: acquisitions, brand-mandated PIPs, FF&E and refinances.",
        ["SBA 7(a) & 504", "Bridge to perm", "Up to 90% LTV"],
        "$500K-$25M",
      ),
      make(
        "cafe-financing",
        "Café & Coffee Shop Financing",
        Coffee,
        "Espresso bars to roasteries",
        "Equipment-heavy financing for cafés, roasters and specialty coffee concepts, including Wynwood's growing third-wave roastery cluster.",
        ["Equipment + working capital", "Soft credit pre-qual", "No prepayment penalty"],
        "From $15K",
      ),
    ],
  },
  {
    slug: "transportation",
    label: "Transportation & Logistics",
    icon: Truck,
    hero: "Keep the fleet rolling.",
    intro:
      "From PortMiami drayage and MIA cargo to Doral 3PLs: trucks, trailers, repair bays and the working capital that holds the Latin American trade gateway together.",
    services: [
      make(
        "trucking-business-loans",
        "Trucking Business Loans",
        Truck,
        "Owner-operators to fleet expansion",
        "Capital to add tractors, cover insurance down payments, fuel up and bridge slow-pay receivables, built for PortMiami and MIA cargo economics.",
        ["DOT-friendly underwriting", "Factoring + term combos", "Fuel & maintenance reserves"],
        "Funded in 24 hours",
      ),
      make(
        "auto-repair-shop-financing",
        "Auto Repair Shop Financing",
        Wrench,
        "Bays, lifts and diagnostics",
        "Equipment and real estate financing for Miami independent shops, collision centers and quick-lube operators.",
        ["Lifts, alignment & ADAS", "Real estate purchase", "Up to 7-year terms"],
        "Rates from 7.5%",
      ),
      make(
        "fleet-vehicle-financing",
        "Fleet & Vehicle Financing",
        Car,
        "Light-duty to heavy fleets",
        "Single units or full fleets: sedans, sprinter vans, box trucks and specialty vehicles with predictable payments, sized for Miami's hospitality, services and import-export economies.",
        ["TRAC leases & loans", "Upfit financing included", "Bundle multiple vehicles"],
        "100% financing",
      ),
      make(
        "logistics-working-capital",
        "Logistics Working Capital",
        Bus,
        "3PL and freight forwarders",
        "Lines of credit and revenue-based financing to scale Doral and Medley logistics operations during peak Latin American trade cycles.",
        ["Same-day draws", "Lines up to $2M", "Revolving structures"],
        "No collateral required",
      ),
    ],
  },
  {
    slug: "retail",
    label: "Retail & Lifestyle",
    icon: ShoppingBag,
    hero: "Stock more. Sell more.",
    intro:
      "Inventory financing, build-outs and working capital for Miami storefronts, salons, gyms and lifestyle retail concepts: Aventura Mall flagships to Wynwood independents.",
    services: [
      make(
        "retail-business-loans",
        "Retail Business Loans",
        ShoppingBag,
        "Inventory & storefront capital",
        "Stock up for the season, open a second location, or refresh your Miami storefront with capital sized to retail cash flow cycles and tourist seasonality.",
        ["Seasonal payment structures", "Inventory financing", "POS-integrated underwriting"],
        "$15K-$1M",
      ),
      make(
        "salon-business-loans",
        "Salon & Med-Spa Loans",
        Scissors,
        "Beauty, wellness & medical aesthetics",
        "Chair rentals, suite build-outs, product inventory, lasers and injectables: capital built for Miami's outsized beauty and aesthetics market.",
        ["Equipment & build-out", "Marketing & inventory", "Med-spa & aesthetics"],
        "Quick pre-qual",
      ),
      make(
        "boutique-storefront-funding",
        "Boutique & Storefront Funding",
        Store,
        "Independent retailers",
        "Pop-ups to permanent locations: working capital and short-term financing for indie brands and boutiques in Design District, Wynwood and Coconut Grove.",
        ["Short-term + revolving", "No equity dilution", "Approvals in 24 hours"],
        "Soft credit pull",
      ),
    ],
  },
  {
    slug: "manufacturing",
    label: "Manufacturing",
    icon: Factory,
    hero: "Capital that scales the line.",
    intro:
      "Heavy equipment, working capital and receivables financing for manufacturers, fabricators and producers across Doral, Medley and South Florida's light-industrial corridor.",
    services: [
      make(
        "manufacturing-equipment-financing",
        "Manufacturing Equipment Financing",
        Cog,
        "CNC, packaging & production lines",
        "Finance individual machines or entire production cells with structures that align to ROI timelines, including soft costs.",
        ["New & used equipment", "Soft costs included", "Step payment options"],
        "Up to $10M",
      ),
      make(
        "working-capital-loans",
        "Working Capital Loans",
        Banknote,
        "Bridge purchase orders & payroll",
        "Cover raw material spikes, fund large purchase orders or bridge customer payment terms without giving up equity.",
        ["Lines up to $5M", "Same-day draws", "Revolving structures"],
        "Funded same week",
      ),
      make(
        "invoice-factoring",
        "Invoice Factoring",
        Receipt,
        "Turn AR into cash today",
        "Sell your invoices for immediate liquidity: non-recourse and recourse options popular with Miami import-export and freight-tied manufacturers.",
        ["Advance rates up to 95%", "Non-recourse available", "No long-term contracts"],
        "24-hour funding",
      ),
      make(
        "accounts-receivable-financing",
        "Accounts Receivable Financing",
        Boxes,
        "Lines secured by your AR",
        "A revolving facility that grows with your receivables, cheaper than factoring when volume is consistent.",
        ["Up to 90% AR advance", "Maintain customer relationships", "Reporting-friendly"],
        "Lines $250K-$20M",
      ),
    ],
  },
  {
    slug: "real-estate",
    label: "Real Estate",
    icon: Home,
    hero: "Build the Miami portfolio.",
    intro:
      "Acquisition, construction and bridge financing for South Florida investors, owner-operators and commercial real estate professionals, in one of the most active CRE markets in the country.",
    services: [
      make(
        "commercial-real-estate-loans",
        "Commercial Real Estate Loans",
        Building,
        "Owner-occupied & investment",
        "Long-term fixed-rate financing for Miami retail, office, industrial and multifamily properties: SBA 504 and conventional CRE for Brickell, Wynwood and Doral.",
        ["Up to 25-year amortization", "90% LTV on owner-occupied", "Cash-out refinance"],
        "$250K-$25M",
      ),
      make(
        "business-acquisition-loans",
        "Business Acquisition Loans",
        Briefcase,
        "Buy the building & the business",
        "Combined acquisition packages that finance the operating business and the real estate it sits on in one closing, common in Coral Gables succession deals.",
        ["10% down with SBA", "Goodwill financing", "Earn-out friendly"],
        "Close in 45-60 days",
      ),
      make(
        "construction-to-perm",
        "Construction-to-Permanent",
        Hammer,
        "Single-close construction",
        "Avoid two closings with a single-close construction-to-permanent loan that converts automatically at certificate of occupancy.",
        ["Single closing", "Lock perm rate early", "Interest-only during build"],
        "Up to $15M",
      ),
      make(
        "bridge-financing",
        "Bridge Financing",
        TrendingUp,
        "Speed when you need it",
        "Short-term bridge capital for value-add Miami acquisitions, reposition plays, 1031 exchanges and condo deconversions.",
        ["6-24 month terms", "Interest-only", "Close in 2 weeks"],
        "Up to 75% LTV",
      ),
    ],
  },
  {
    slug: "professional-services",
    label: "Professional Services",
    icon: Briefcase,
    hero: "Capital for the firm.",
    intro:
      "Tailored financing for Miami law firms, accounting practices, consulting groups, family offices and the international business community that calls Coral Gables and Brickell home.",
    services: [
      make(
        "professional-services-loans",
        "Professional Services Loans",
        Briefcase,
        "Law, accounting & consulting",
        "Partner buy-ins, lateral hires, technology and office build-outs financed around partner draw cycles.",
        ["Unsecured options to $500K", "Partner buy-in financing", "Tech & build-out included"],
        "Soft pull pre-qual",
      ),
      make(
        "business-line-of-credit",
        "Business Line of Credit",
        CreditCard,
        "Draw what you need, when you need it",
        "Revolving capital that's there when AR slows or a new matter ramps up. Only pay interest on what you draw.",
        ["Lines $25K-$500K", "Same-day draws", "Pay interest only on used balance"],
        "Rates from 8.99%",
      ),
      make(
        "unsecured-business-loans",
        "Unsecured Business Loans",
        Scale,
        "No collateral, no liens",
        "Cash-flow-based underwriting for established firms with strong revenue. No UCC blanket liens or personal collateral.",
        ["Funded in 1-3 days", "Terms 1-5 years", "No equity required"],
        "Up to $500K",
      ),
      make(
        "loan-broker-services",
        "Business & Commercial Loan Brokering",
        Calculator,
        "We shop our lender network for you",
        "Access 75+ vetted lenders through one application. Bilingual specialists familiar with Latin American cross-border structures.",
        ["75+ lender network", "Bilingual EN/ES", "We negotiate on your behalf"],
        "No fee until close",
      ),
    ],
  },
  {
    slug: "technology",
    label: "Technology",
    icon: Cpu,
    hero: "Non-dilutive growth capital.",
    intro:
      "Revenue-based financing, lines of credit and equipment leases for the Miami tech cluster: Wynwood-anchored SaaS, eMerge-driven startups, and the international tech operators using Miami as their Americas HQ.",
    services: [
      make(
        "revenue-based-financing",
        "Revenue-Based Financing",
        LineChart,
        "Pay as you earn",
        "Capital priced as a fixed multiple, repaid as a percentage of monthly revenue. No equity, no fixed installments.",
        ["No equity dilution", "No personal guarantee*", "Flexible repayment"],
        "$50K-$5M",
      ),
      make(
        "sba-loan-for-franchise",
        "SBA Loan for Tech & Franchise",
        Sparkles,
        "SBA 7(a) for tech-enabled franchises",
        "Long-term fixed financing for franchise owners and tech-enabled service businesses. Leverage SBA terms for scale.",
        ["Up to 10-year terms", "10% down typical", "Low fixed rates"],
        "Up to $5M",
      ),
      make(
        "tech-equipment-leasing",
        "Tech Equipment Leasing",
        Laptop,
        "Servers, devices & cloud",
        "Lease laptops, servers and AV equipment with built-in refresh cycles. Operational expense treatment.",
        ["24-60 month terms", "Refresh built in", "Bundled service"],
        "From $10K",
      ),
      make(
        "growth-marketing-capital",
        "Growth & Marketing Capital",
        Megaphone,
        "Fund the acquisition flywheel",
        "Working capital sized for ad spend and growth campaigns with payback structured to CAC payback periods.",
        ["Up to $2M", "Flexible draws", "Performance-aligned"],
        "Funded in 48 hours",
      ),
    ],
  },
  {
    slug: "e-commerce",
    label: "E-Commerce",
    icon: Globe,
    hero: "Capital that ships.",
    intro:
      "Inventory financing, ad spend capital and working capital for Miami DTC brands, marketplace sellers and omnichannel retailers shipping out of South Florida fulfillment centers to Latin America and the U.S.",
    services: [
      make(
        "ecommerce-business-funding",
        "E-Commerce Business Funding",
        Globe,
        "Inventory & ad spend capital",
        "Capital sized to your AOV, repeat rate and marketing payback, purpose-built for Shopify, Amazon and DTC brands.",
        ["Integrates with Shopify & Amazon", "Daily or weekly remittance", "Scales with revenue"],
        "$25K-$3M",
      ),
      make(
        "inventory-financing",
        "Inventory Financing",
        Package,
        "Land the next PO",
        "Finance inbound inventory with terms aligned to your sell-through cycle, perfect for seasonal SKUs and BFCM ramps, sized for South Florida 3PL operators.",
        ["Up to 80% of cost", "Pay as you sell", "Multi-SKU support"],
        "Pre-approve in 24 hours",
      ),
      make(
        "merchant-cash-advance",
        "Merchant Cash Advance",
        ShoppingCart,
        "Fast capital against future sales",
        "An advance against future card and platform sales, funded fast and repaid as a small percentage of daily revenue.",
        ["24-hour funding", "No fixed payments", "Bad credit considered"],
        "$10K-$1M",
      ),
      make(
        "short-term-business-loans",
        "Short-Term Business Loans",
        Banknote,
        "Bridge the next 3-18 months",
        "Fixed-term capital for inventory pre-buys, marketing pushes and short-window opportunities.",
        ["3-18 month terms", "Daily or weekly payments", "No prepayment penalty"],
        "Funded same week",
      ),
    ],
  },
];

export function getIndustry(slug: string): Industry | undefined {
  return INDUSTRIES.find((i) => i.slug === slug);
}
