/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MiamiRouteImport } from './routes/miami'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyNowRouteImport } from './routes/apply-now'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PillarSlugRouteImport } from './routes/pillar.$slug'
import { Route as MiamiSuburbRouteImport } from './routes/miami.$suburb'
import { Route as IndustrySlugRouteImport } from './routes/industry.$slug'
import { Route as MiamiSuburbPillarRouteImport } from './routes/miami.$suburb.$pillar'

const MiamiRoute = MiamiRouteImport.update({
  id: '/miami',
  path: '/miami',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyNowRoute = ApplyNowRouteImport.update({
  id: '/apply-now',
  path: '/apply-now',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarSlugRoute = PillarSlugRouteImport.update({
  id: '/pillar/$slug',
  path: '/pillar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MiamiSuburbRoute = MiamiSuburbRouteImport.update({
  id: '/$suburb',
  path: '/$suburb',
  getParentRoute: () => MiamiRoute,
} as any)
const IndustrySlugRoute = IndustrySlugRouteImport.update({
  id: '/industry/$slug',
  path: '/industry/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MiamiSuburbPillarRoute = MiamiSuburbPillarRouteImport.update({
  id: '/$pillar',
  path: '/$pillar',
  getParentRoute: () => MiamiSuburbRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/miami': typeof MiamiRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/miami/$suburb': typeof MiamiSuburbRouteWithChildren
  '/pillar/$slug': typeof PillarSlugRoute
  '/miami/$suburb/$pillar': typeof MiamiSuburbPillarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/miami': typeof MiamiRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/miami/$suburb': typeof MiamiSuburbRouteWithChildren
  '/pillar/$slug': typeof PillarSlugRoute
  '/miami/$suburb/$pillar': typeof MiamiSuburbPillarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/miami': typeof MiamiRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/miami/$suburb': typeof MiamiSuburbRouteWithChildren
  '/pillar/$slug': typeof PillarSlugRoute
  '/miami/$suburb/$pillar': typeof MiamiSuburbPillarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply-now'
    | '/contact'
    | '/miami'
    | '/industry/$slug'
    | '/miami/$suburb'
    | '/pillar/$slug'
    | '/miami/$suburb/$pillar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply-now'
    | '/contact'
    | '/miami'
    | '/industry/$slug'
    | '/miami/$suburb'
    | '/pillar/$slug'
    | '/miami/$suburb/$pillar'
  id:
    | '__root__'
    | '/'
    | '/apply-now'
    | '/contact'
    | '/miami'
    | '/industry/$slug'
    | '/miami/$suburb'
    | '/pillar/$slug'
    | '/miami/$suburb/$pillar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyNowRoute: typeof ApplyNowRoute
  ContactRoute: typeof ContactRoute
  MiamiRoute: typeof MiamiRouteWithChildren
  IndustrySlugRoute: typeof IndustrySlugRoute
  PillarSlugRoute: typeof PillarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/miami': {
      id: '/miami'
      path: '/miami'
      fullPath: '/miami'
      preLoaderRoute: typeof MiamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-now': {
      id: '/apply-now'
      path: '/apply-now'
      fullPath: '/apply-now'
      preLoaderRoute: typeof ApplyNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillar/$slug': {
      id: '/pillar/$slug'
      path: '/pillar/$slug'
      fullPath: '/pillar/$slug'
      preLoaderRoute: typeof PillarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miami/$suburb': {
      id: '/miami/$suburb'
      path: '/$suburb'
      fullPath: '/miami/$suburb'
      preLoaderRoute: typeof MiamiSuburbRouteImport
      parentRoute: typeof MiamiRoute
    }
    '/industry/$slug': {
      id: '/industry/$slug'
      path: '/industry/$slug'
      fullPath: '/industry/$slug'
      preLoaderRoute: typeof IndustrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miami/$suburb/$pillar': {
      id: '/miami/$suburb/$pillar'
      path: '/$pillar'
      fullPath: '/miami/$suburb/$pillar'
      preLoaderRoute: typeof MiamiSuburbPillarRouteImport
      parentRoute: typeof MiamiSuburbRoute
    }
  }
}

interface MiamiSuburbRouteChildren {
  MiamiSuburbPillarRoute: typeof MiamiSuburbPillarRoute
}

const MiamiSuburbRouteChildren: MiamiSuburbRouteChildren = {
  MiamiSuburbPillarRoute: MiamiSuburbPillarRoute,
}

const MiamiSuburbRouteWithChildren = MiamiSuburbRoute._addFileChildren(
  MiamiSuburbRouteChildren,
)

interface MiamiRouteChildren {
  MiamiSuburbRoute: typeof MiamiSuburbRouteWithChildren
}

const MiamiRouteChildren: MiamiRouteChildren = {
  MiamiSuburbRoute: MiamiSuburbRouteWithChildren,
}

const MiamiRouteWithChildren = MiamiRoute._addFileChildren(MiamiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyNowRoute: ApplyNowRoute,
  ContactRoute: ContactRoute,
  MiamiRoute: MiamiRouteWithChildren,
  IndustrySlugRoute: IndustrySlugRoute,
  PillarSlugRoute: PillarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
